languageCode = "en-us"
title = "John Goulah"
theme = "beautifulhugo"
#theme = "ananke"
baseURL = "https://blog.johngoulah.com/"
relativeURLs = false
googleAnalytics = "UA-7020489-1"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "hacking / management / systems"
  rss = true
  logo = "img/jg-crop1.png" # Expecting square dimensions

[Author]
  name = "John Goulah"
  website = "blog.johngoulah.com"
  #email = "youremail@domain.com"
  github = "jgoulah"
  twitter = "johngoulah"
  linkedin = "goulah"
  #slack = "jgoulah"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[[menu.main]]
    name = "Tech"
    url = "post/tech"
    weight = 1

[[menu.main]]
    name = "Mgmt"
    url = "post/mgmt"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    identifier = "all"
    name = "More"
    weight = 4

[[menu.main]]
    parent = "all"
    name = "Posts"
    url = "post"
    weight = 2

[[menu.main]]
    parent = "all"
    name = "Tags"
    url = "tags"
    weight = 2
